"""Hardware abstraction layer for the Sparky device runtime.

Application code depends on the ports in :mod:`sparky_device.hardware.ports`
and obtains an implementation from :func:`create_ports`. The SunFounder
libraries (``pidog``, ``robot_hat``, ``vilib``) are imported lazily inside the
adapters, so importing this package never requires a Raspberry Pi.

    from sparky_device.hardware import create_ports

    with create_ports() as robot:
        robot.motion.do_action("sit")
"""

from __future__ import annotations

from .factory import (
    AUTO_PROFILE,
    HARDWARE_ENV_VAR,
    PIDOG_PROFILE,
    SIMULATOR_PROFILE,
    VALID_PROFILES,
    create_ports,
    resolve_profile,
)
from .pidog_adapters import (
    PidogBoardAdapter,
    PidogMicrophoneAdapter,
    PidogMotionAdapter,
    PidogSensorAdapter,
    PidogSpeakerAdapter,
    VilibCameraAdapter,
    build_pidog_ports,
    vendor_libraries_available,
)
from .ports import (
    AUDIO_MAX_CHANNELS,
    AUDIO_SAMPLE_WIDTHS,
    AudioChunk,
    DEFAULT_LIMITS,
    HEAD_JOINT_COUNT,
    LEG_JOINT_COUNT,
    BoardPort,
    CameraPort,
    Frame,
    HardwareError,
    HardwareUnavailableError,
    ImuReading,
    MicrophonePort,
    MotionLimits,
    MotionPort,
    MOTION_ACTIONS,
    RgbColor,
    RGB_STYLES,
    RobotPorts,
    SensorPort,
    ServoRange,
    SpeakerPort,
    TouchState,
    VILIB_CAPTURE_SIZE,
    validate_action_name,
    validate_audio_format,
    validate_camera_resolution,
    validate_rgb_style,
)
from .simulators import (
    MotionCommand,
    RgbCommand,
    SimulatedBoard,
    SimulatedCamera,
    SimulatedMicrophone,
    SimulatedMotion,
    SimulatedSensors,
    SimulatedSpeaker,
    SoundCommand,
    PlaybackCommand,
    build_simulated_ports,
    load_frame_fixtures,
    load_wav_fixture,
    solid_frame,
)

__all__ = [
    "AUDIO_MAX_CHANNELS",
    "AUDIO_SAMPLE_WIDTHS",
    "AUTO_PROFILE",
    "AudioChunk",
    "DEFAULT_LIMITS",
    "HARDWARE_ENV_VAR",
    "HEAD_JOINT_COUNT",
    "LEG_JOINT_COUNT",
    "PIDOG_PROFILE",
    "SIMULATOR_PROFILE",
    "VALID_PROFILES",
    "BoardPort",
    "CameraPort",
    "Frame",
    "HardwareError",
    "HardwareUnavailableError",
    "ImuReading",
    "MicrophonePort",
    "MotionCommand",
    "MotionLimits",
    "MotionPort",
    "MOTION_ACTIONS",
    "PidogBoardAdapter",
    "PidogMicrophoneAdapter",
    "PidogMotionAdapter",
    "PidogSensorAdapter",
    "PidogSpeakerAdapter",
    "PlaybackCommand",
    "RgbColor",
    "RGB_STYLES",
    "RgbCommand",
    "RobotPorts",
    "SensorPort",
    "ServoRange",
    "SimulatedBoard",
    "SimulatedCamera",
    "SimulatedMicrophone",
    "SimulatedMotion",
    "SimulatedSensors",
    "SimulatedSpeaker",
    "SoundCommand",
    "SpeakerPort",
    "TouchState",
    "VILIB_CAPTURE_SIZE",
    "VilibCameraAdapter",
    "build_pidog_ports",
    "build_simulated_ports",
    "create_ports",
    "load_frame_fixtures",
    "load_wav_fixture",
    "resolve_profile",
    "solid_frame",
    "validate_action_name",
    "validate_audio_format",
    "validate_camera_resolution",
    "validate_rgb_style",
    "vendor_libraries_available",
]
